# Generated by Django 4.0 on 2022-01-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_book_isbn_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='username',
        ),
    ]
