# Generated by Django 4.0 on 2022-01-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_genre_remove_book_genres_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20, unique=True)),
        ),
    ]
