# Generated by Django 4.0 on 2022-01-04 18:23

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='url',
            field=models.URLField(default=builtins.id),
        ),
    ]
