# Generated by Django 4.0 on 2022-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_genre_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
