# Generated by Django 4.0 on 2022-01-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_alter_genre_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
