# Generated by Django 4.0 on 2022-01-09 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_alter_opinion_book_alter_opinion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
