# Generated by Django 4.0 on 2022-01-09 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0015_opinion_date_opinion_rating_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
