# Generated by Django 4.0 on 2022-01-09 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_alter_opinion_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
